const list = [
    {
      id: 1,
      title: "Redmi Note 11",
      Specifications:"Redmi Note 11 (Horizon Blue, 6GB RAM, 128GB Storage)|90Hz FHD+ AMOLED Display | Qualcomm® Snapdragon™ 680-6nm | Alexa Built-in | 33W Charger Included               ",
      price: 15999,
      img: "https://m.media-amazon.com/images/I/81zLNgcvlaL._SL1500_.jpg",
      amount: 1,
    },
    {
      id: 2,
      title: "Redmi Note 10S ",
      Specifications : "Redmi Note 10S (Frost White, 6GB RAM, 64GB Storage) -        Super Amoled Display | 64 MP Quad Camera |       Alexa Built in | 33W Charger Included                   ",
      price: 12999,
      img: "https://m.media-amazon.com/images/I/81SJHWh-dfL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 3,
      title: "Redmi Note 11S ",
      Specifications : "Redmi Note 11S (Space Black, 8GB RAM, 128GB Storage)|108MP AI Quad Camera   | 90 Hz FHD+ AMOLED Display   | 33W Charger Included |   Additional Exchange Offers         ",
      price: 18499,
      img: "https://m.media-amazon.com/images/I/71kFQTnr3eL._SL1500_.jpg",
      amount: 1,
    },
    {
      id: 4,
      title: "Vivo Y33T",
      Specifications : "Vivo Y33T (Mirror Black, 8GB RAM, 128GB ROM)|50MP+2MP+2MP Rear Camera | 16MP Selfie Camera16.71cm 6.58                                                            ",
      price: 17990,
      img:"https://images-eu.ssl-images-amazon.com/images/I/41CC7ePoD2L._SX300_SY300_QL70_FMwebp_.jpg",
      amount: 1,
    },
    {
        id: 5,
        title: "Vivo V20 SE",
        Specifications : "Vivo V20 SE (Aquamarine Green, 8GB RAM, 128GB ROM)|48MP+5MP+2MP Rear Camera | 32MP Selfie Camera|16.37 centimeters (6.44-inch)                                  ",
        price: 19000,
        img: "https://m.media-amazon.com/images/I/61SpgTRKPkL._SL1200_.jpg",
        amount: 1,
      },
      {
        id: 6,
        title: "Vivo V19",
        Specifications : "(Renewed) Vivo V19 Mystic Silver, 8GB RAM, 128GB Storage16.36 centimeters (6.44-inch) FHD+ LIV (E3) Super AMOLED with 2400 x 1080 pixels resolution | In-Display",
        price: 19599,
        img: "https://m.media-amazon.com/images/I/61DlqYmSLOL._SL1024_.jpg",
        amount: 1,
      },
      {
        id: 7,
        title: "Vivo Y73",
        Specifications : "Vivo Y73 (Diamond Flare, 8GB RAM, 128GB Storage)|64MP+2MP+2MP Rear Camera | 16MP Selfie Camera 16cm Display with 2400 x 1080 pixels resolution.                 ",
        price: 19989,
        img: "https://m.media-amazon.com/images/I/511oJE35CxS._AC_SX410_SY308_.jpg",
        amount: 1,
      },
      {
        id: 8,
        title: "Samsung Galaxy M33 5G",
        Specifications : " Samsung Galaxy M33 5G (Deep Ocean Blue, 8GB, 128GB Storage) | Travel Adapter to be Purchased Separately                                                        ",
        price: 19499,
        img: "https://m.media-amazon.com/images/I/81xvGbBFNhL._AC_UY327_FMwebp_QL65_.jpg",
        amount: 1,
      },
      {
        id: 9,
        title: "Samsung Galaxy M53 5G",
        Specifications : "Samsung Galaxy M53 5G (Mystique Green, 6GB, 128GB Storage) | Travel Adapter to be Purchased Separately                                                          ",
        price: 26499,
        img: "https://m.media-amazon.com/images/I/71MaDLgHnxL._SX679_.jpg",
        amount: 1,
      },
      {
        id: 10,
        title: "Apple iPhone 13 (128GB)",
        Specifications : "Apple iPhone 13 (128GB) - Blue|15 cm (6.1-inch) Super Retina XDR displayAdvanced dual-camera system with 12MP Wide and Ultra Wide cameras; Photographic Styles  ",
        price: 77990,
        img: "https://m.media-amazon.com/images/I/71xb2xkN5qL._SX569_.jpg",
        amount: 1,
      },
    
    {
      id: 11,
     title :"Apple iPhone 12",
     Specifications:"Apple iPhone 12 (64GB) - White|6.1-inch (15.5 cm diagonal) Super Retina XDR display Ceramic Shield| tougher than any smartphone glass                                ",
     price:54900,
     img :"https://m.media-amazon.com/images/I/711wsjBtWeL._SX569_.jpg",
     amount: 1,
    },
    {
      id: 12,
     title:" Apple 10.2-inch (25.91 cm) iPad with A13",
     Specifications:"2021 Apple 10.2-inch  iPad with A13 Bionic chip (Wi-Fi, 64GB)-Space Grey (9th Generation)|8MP Wide back camera, 12MP Ultra Wide front camera with Centre Stage       ",
     price:"30400",
     img :"https://m.media-amazon.com/images/I/61NGnpjoRDL._AC_UY327_FMwebp_QL65_.jpg",
    amount: 1,
     
    },
  ];
  
  export default list;